// Cross-decode unit tests for formats/mef.js — validates our JS RED
// decoder against REAL C-encoded MEF3 bytes produced by pymef 1.4.x
// (the official Mayo Clinic Python wrapper).
//
// The synthetic fixture (mef-tiny.mefd/) only round-trips through OUR
// encoder + decoder, which means a bug in both sides would go silently
// undetected. This test fixes that gap: pymef calls into meflib.c
// (Mayo's authoritative C reference implementation), so any byte-level
// drift here is a real interop bug in the JS reader.
//
// The fixture is generated by scripts/make-mef-pymef-fixture.py and
// also exercises the BIDS-canonical `.segd/` segment subdirectory
// layout that listSegmentsFromDirectory must descend into.
//
// Re-run the fixture generator if pymef is upgraded:
//   /path/to/python scripts/make-mef-pymef-fixture.py

import { test } from 'node:test';
import { strict as assert } from 'node:assert';
import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';

const require = createRequire(import.meta.url);
require('../formats/_buffers.js');
require('../formats/_labels.js');
require('../formats/_decode.js');
require('../formats/_mef-segment.js');
require('../formats/_mef-red.js');
const MefReader = require('../formats/mef.js');

const FIXTURE_DIR = path.resolve('tests/fixtures/ieeg/mef-pymef-real.mefd');
const FIXTURE_URL = 'file://' + FIXTURE_DIR + '/';
const CHANNELS = ['A1', 'A2', 'A3', 'A4'];

// Deterministic sine generator — must match scripts/make-mef-pymef-fixture.py.
const CHANNEL_FREQ = { A1: 10, A2: 20, A3: 40, A4: 80 };
const SAMPLE_RATE  = 1000;
function expectedSample(chName, i) {
  const v = Math.round(1000 * Math.sin(2 * Math.PI * CHANNEL_FREQ[chName] * i / SAMPLE_RATE));
  return v === 0 ? 0 : v;
}

// Skip every test in this file when the fixture is missing — the
// generator script depends on pymef which isn't a JS dependency.
const FIXTURE_AVAILABLE = fs.existsSync(FIXTURE_DIR);
const skipIfNoFixture = FIXTURE_AVAILABLE
  ? false
  : 'pymef fixture missing; run scripts/make-mef-pymef-fixture.py';

function installLocalHttpRange() {
  globalThis.HttpRange = {
    async probeLength(url) {
      return fs.statSync(url.replace(/^file:\/\//, '')).size;
    },
    async probeLengthNoHead(url) {
      return fs.statSync(url.replace(/^file:\/\//, '')).size;
    },
    async fetchBuffer(url) {
      const b = fs.readFileSync(url.replace(/^file:\/\//, ''));
      return b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength);
    },
    async rangeFetch(url, start, endIncl) {
      const b = fs.readFileSync(url.replace(/^file:\/\//, ''));
      const slice = b.slice(start, endIncl + 1);
      return slice.buffer.slice(slice.byteOffset, slice.byteOffset + slice.byteLength);
    },
    async listDir(url) {
      const dir = url.replace(/^file:\/\//, '').replace(/\/$/, '');
      return fs.readdirSync(dir);
    },
  };
}

// ─── BIDS-spec .segd/ layout walk ────────────────────────────────

test('mef-real: listSegmentsFromDirectory descends into .segd/ subdir', { skip: skipIfNoFixture }, async () => {
  installLocalHttpRange();
  const r = await MefReader.open({ eeg_url: FIXTURE_URL });
  assert.equal(r.n_channels, 4, 'expected 4 channels from pymef fixture');
  assert.equal(r.sampling_frequency, 1000);
  assert.equal(r.n_samples, 2500);
  assert.deepEqual([...r.channel_labels].sort(), CHANNELS);
  // _mef debug surface: each channel's segment_dir should be inside .segd/.
  for (const ch of r._mef.channels) {
    assert.match(
      ch.tmet_url || '',
      /\.segd\/[^/]+\.tmet$/,
      `channel ${ch.channel_name} tmet_url does not point inside .segd/: ${ch.tmet_url}`,
    );
  }
});

// ─── Byte-level cross-decode (the lane K MEDIUM→HIGH check) ──────

test('mef-real: readWindow matches the deterministic sine bytes encoded by pymef (head 100)', { skip: skipIfNoFixture }, async () => {
  installLocalHttpRange();
  const r = await MefReader.open({ eeg_url: FIXTURE_URL });
  const N = 100;
  const win = await r.readWindow(0, N);
  assert.equal(win.length, 4, 'one Float32Array per channel');
  assert.equal(win[0].length, N);

  for (let c = 0; c < 4; c++) {
    const ch = r.channel_labels[c];
    for (let i = 0; i < N; i++) {
      const expected = expectedSample(ch, i);
      // Float32 has plenty of precision for ±1000-amplitude integers.
      assert.equal(
        win[c][i], expected,
        `channel ${ch} sample ${i}: got ${win[c][i]} expected ${expected}`,
      );
    }
  }
});

test('mef-real: readWindow stitches across pymef RED block boundary', { skip: skipIfNoFixture }, async () => {
  // pymef writes 500-sample blocks (samps_per_mef_block=500 in the
  // fixture generator). Read across the first→second block boundary.
  installLocalHttpRange();
  const r = await MefReader.open({ eeg_url: FIXTURE_URL });
  const start = 450, N = 100;
  const win = await r.readWindow(start, N);
  for (let c = 0; c < 4; c++) {
    const ch = r.channel_labels[c];
    for (let i = 0; i < N; i++) {
      const expected = expectedSample(ch, start + i);
      assert.equal(
        win[c][i], expected,
        `channel ${ch} sample ${start + i}: got ${win[c][i]} expected ${expected}`,
      );
    }
  }
});

test('mef-real: full-recording read agrees with sine ground truth', { skip: skipIfNoFixture }, async () => {
  installLocalHttpRange();
  const r = await MefReader.open({ eeg_url: FIXTURE_URL });
  const win = await r.readWindow(0, r.n_samples);
  // Spot-check first sample of every block + last sample for every channel.
  for (let c = 0; c < 4; c++) {
    const ch = r.channel_labels[c];
    for (let block = 0; block < 5; block++) {
      const idx = block * 500;
      assert.equal(
        win[c][idx], expectedSample(ch, idx),
        `channel ${ch} block-${block} first sample (idx ${idx})`,
      );
    }
    const last = r.n_samples - 1;
    assert.equal(win[c][last], expectedSample(ch, last),
      `channel ${ch} last sample (idx ${last})`);
  }
});

