# /// script
# dependencies = ["mne==1.11.0"]
# ///
"""Regenerate the bundled EEG template: uv run scripts/export-sensor-montage.py."""
import json
from pathlib import Path

import mne
from mne.bem import fit_sphere_to_headshape
from mne.transforms import apply_trans, invert_transform
import numpy as np
from scipy.spatial import cKDTree

montage = mne.channels.make_standard_montage("standard_1020")
montage.apply_trans(mne.channels.compute_native_head_t(montage))
positions = montage.get_positions()
info = mne.create_info(montage.ch_names, 1, "eeg")
info.set_montage(montage)
radius, centre, _ = fit_sphere_to_headshape(info, dig_kinds="eeg", units="m", verbose=False)
points = {name: [round(float(v), 7) for v in xyz]
          for name, xyz in positions["ch_pos"].items()}
atlas = Path(mne.__file__).parent / "data" / "fsaverage"
surface = mne.read_bem_surfaces(atlas / "fsaverage-head.fif", verbose=False)[0]
vertices = apply_trans(invert_transform(mne.read_trans(atlas / "fsaverage-trans.fif")), surface["rr"])
# Independent geometric check: the electrode template must lie near the scalp.
distances = cKDTree(vertices).query(list(points.values()))[0]
assert np.median(distances) < 0.015, f"Montage/scalp frame mismatch: {np.median(distances)} m"
assert surface["tris"].min() >= 0 and surface["tris"].max() < len(vertices)
head = {"radius": float(radius), "centre": centre.tolist(),
        "vertices": np.round(vertices * 1000, 4).tolist(),
        "triangles": surface["tris"].tolist(),
        "source": "MNE fsaverage scalp", "space": "MNE head", "units": "mm"}
target = Path(__file__).resolve().parents[1] / "sensor-montage.js"
target.write_text(
    "// MNE-Python 1.11.0 standard_1020, transformed to head RAS, metres.\n"
    "// Template positions, not participant digitization. See docs/sensor-geometry.md.\n"
    "// Generated by scripts/export-sensor-montage.py; MNE BSD license: docs/MNE-LICENSE.txt.\n"
    "globalThis.SensorMontage = " + json.dumps(points, separators=(",", ":")) + ";\n"
    "globalThis.SensorHead = " + json.dumps(head, separators=(",", ":")) + ";\n"
)
print(f"Exported {len(points)} positions and {len(surface['tris'])} scalp triangles to {target}")
print(f"Median montage/scalp distance: {np.median(distances) * 1000:.2f} mm")
