#!/usr/bin/env python3
"""
Generate a real C-encoded MEF3 fixture via pymef 1.4.x.

This complements scripts/make-mef-fixture.mjs (which uses our pure-JS
RED encoder) by producing ground-truth bytes from the official Mayo
Clinic Python wrapper. The cross-decode test
tests/unit-mef-real.test.mjs reads this fixture and verifies our
JS RED decoder agrees with samples generated by the C codec.

Output layout matches the BIDS-spec MEF3 directory tree, with the
real `.segd/` segment subdirectory:

    tests/fixtures/ieeg/mef-pymef-real.mefd/
      A1.timd/
        A1-000000.segd/
          A1-000000.tmet
          A1-000000.tdat
          A1-000000.tidx
      A2.timd/...
      A3.timd/...
      A4.timd/...

Channels:
    A1: 10 Hz, A2: 20 Hz, A3: 40 Hz, A4: 80 Hz; amplitude 1000.
    1000 Hz, 2500 samples (2.5 s), no encryption.

Re-run when bumping the pymef dependency. The fixture is committed
under tests/fixtures/ieeg/ — small (a few KB) and deterministic.
"""
from __future__ import annotations

import math
import os
import shutil
import sys
from pathlib import Path

import numpy as np

try:
    from pymef.mef_session import MefSession
except ImportError as exc:
    sys.stderr.write(
        "pymef is not installed in this Python. Install via:\n"
        "  pip install pymef==1.4.*\n"
    )
    raise


REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_DIR = REPO_ROOT / "tests" / "fixtures" / "ieeg" / "mef-pymef-real.mefd"

# Must match tests/unit-mef-real.test.mjs.
CHANNEL_FREQ = {"A1": 10, "A2": 20, "A3": 40, "A4": 80}
SAMPLE_RATE = 1000
N_SAMPLES = 2500
SAMPS_PER_BLOCK = 500
AMPLITUDE = 1000

# 2026-01-01T00:00:00Z in μUTC (matches the JS-encoded fixture so we can
# reuse the same recording_start_iso assertion if we like).
START_TIME_UUTC = 1767225600_000000
END_TIME_UUTC = START_TIME_UUTC + int(1e6 * N_SAMPLES / SAMPLE_RATE)
REC_OFFSET = START_TIME_UUTC - int(1e6)


def synthesize_channel(name: str) -> np.ndarray:
    """Deterministic integer sine, identical formula to the JS fixture."""
    freq = CHANNEL_FREQ[name]
    samples = np.zeros(N_SAMPLES, dtype=np.int32)
    for i in range(N_SAMPLES):
        samples[i] = int(round(AMPLITUDE * math.sin(2 * math.pi * freq * i / SAMPLE_RATE)))
    return samples


def section_2_dict(channel_name: str) -> dict:
    """Section-2 time-series metadata. pymef fills C-computed fields itself."""
    return {
        "channel_description": channel_name.encode("ascii"),
        "session_description": b"mef-pymef-real",
        "recording_duration": 1,  # pymef recomputes on write
        "reference_description": b"none",
        "acquisition_channel_number": 1,
        "sampling_frequency": float(SAMPLE_RATE),
        "notch_filter_frequency_setting": 0.0,
        "low_frequency_filter_setting": 0.0,
        "high_frequency_filter_setting": 0.0,
        "AC_line_frequency": 60,
        "units_conversion_factor": 1.0,
        "units_description": b"uV",
        "maximum_native_sample_value": 0.0,
        "minimum_native_sample_value": 0.0,
        "start_sample": 0,
        "number_of_blocks": 0,
        "maximum_block_bytes": 0,
        "maximum_block_samples": 0,
        "maximum_difference_bytes": 0,
        "block_interval": 0,
        "number_of_discontinuities": 1,
        "maximum_contiguous_blocks": 0,
        "maximum_contiguous_block_bytes": 0,
        "maximum_contiguous_samples": 0,
        "number_of_samples": 0,
    }


def section_3_dict() -> dict:
    return {
        "recording_time_offset": REC_OFFSET,
        "DST_start_time": 0,
        "DST_end_time": 0,
        "GMT_offset": 0,
        "subject_name_1": b"fixture",
        "subject_name_2": b"pymef",
        "subject_ID": b"0000",
        "recording_location": b"local",
    }


def main() -> int:
    # Clean stale fixture so we always produce a fresh tree.
    if FIXTURE_DIR.exists():
        shutil.rmtree(FIXTURE_DIR)
    FIXTURE_DIR.mkdir(parents=True)

    # MefSession requires a non-empty password to "open" the session even
    # when we want to write *unencrypted* segments. The password is only
    # used for encryption; we just don't pass it to write_mef_records etc.
    # for any encrypted level. We pass None for password_1/2 below so the
    # output bytes carry no encryption.
    sess_pwd = "fixture"
    ms = MefSession(str(FIXTURE_DIR), sess_pwd, read_metadata=False)

    try:
        for channel_name in CHANNEL_FREQ:
            data = synthesize_channel(channel_name)

            sec2 = section_2_dict(channel_name)
            sec3 = section_3_dict()

            # Segment 0 only (single-segment fixture).
            ms.write_mef_ts_segment_metadata(
                channel_name,
                0,
                None,            # password_1 — None = no L1 encryption
                None,            # password_2 — None = no L2 encryption
                START_TIME_UUTC,
                END_TIME_UUTC,
                sec2,
                sec3,
            )

            ms.write_mef_ts_segment_data(
                channel_name,
                0,
                None,
                None,
                SAMPS_PER_BLOCK,
                data,
            )
    finally:
        ms.close()

    # Verify on-disk layout — the BIDS spec uses an inner .segd/ subdir.
    for channel_name in CHANNEL_FREQ:
        seg_dir = FIXTURE_DIR / f"{channel_name}.timd" / f"{channel_name}-000000.segd"
        if not seg_dir.is_dir():
            sys.stderr.write(
                f"FAIL: expected segd subdir {seg_dir} not produced by pymef "
                f"(pymef API changed?)\n"
            )
            return 1
        for ext in ("tmet", "tdat", "tidx"):
            f = seg_dir / f"{channel_name}-000000.{ext}"
            if not f.is_file() or f.stat().st_size == 0:
                sys.stderr.write(
                    f"FAIL: missing/empty {f} after pymef write\n"
                )
                return 1

    rel = FIXTURE_DIR.relative_to(REPO_ROOT)
    print(f"wrote pymef MEF3 fixture: {rel}")
    print(f"  channels: {list(CHANNEL_FREQ)}")
    print(f"  sample_rate: {SAMPLE_RATE} Hz")
    print(f"  n_samples: {N_SAMPLES}")
    print(f"  layout: <channel>.timd/<channel>-000000.segd/<channel>-000000.{{tmet,tdat,tidx}}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
